### ISSUE TITLE
npm run build - path not string

### ISSUE THREAD

**Issue by markfirmware** [argyleink/snowpack-template-preset-env#6]
npm run build
   
    > @ build /root/github.com/markfirmware/abc
    > snowpack build
    
    [snowpack] ! building source…
    postcss.plugin was deprecated. Migration guide:
    https://evilmartians.com/chronicles/postcss-8-plugin-migration
    [snowpack] ✔ build complete [2.51s]
    
    TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
        at validateString (internal/validators.js:125:11)
        at Object.join (path.js:1147:7)
        at installDependencies (/root/github.com/markfirmware/abc/node_modules/snowpack/lib/commands/build.js:326:44)
        at Object.command (/root/github.com/markfirmware/abc/node_modules/snowpack/lib/commands/build.js:381:31)
        at process._tickCallback (internal/process/next_tick.js:68:7)
    
    npm ERR! code ELIFECYCLE
    npm ERR! errno 1
    npm ERR! @ build: `snowpack build`
    npm ERR! Exit status 1
    npm ERR! 
    npm ERR! Failed at the @ build script.
    npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
    
    npm ERR! A complete log of this run can be found in:
    npm ERR!     /root/.npm/_logs/2020-11-17T21_30_33_485Z-debug.log

**Comment by markfirmware** [comment]
FYI https://github.com/snowpackjs/snowpack/discussions/1634
